'use client'

/* eslint-disable no-unused-vars */
// Extracted from the former monolithic app/page.js (refactor: June 2025).
// Uniform import header — unused imports are tolerated intentionally.

import React, { useEffect, useMemo, useCallback, useRef, useState } from 'react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter, DialogTrigger } from '@/components/ui/dialog'
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle, AlertDialogTrigger } from '@/components/ui/alert-dialog'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table'
import { toast } from 'sonner'
import { Boxes, AlertTriangle, Clock, PackageX, Plus, Search, Download, ArrowUpDown, Pencil, Trash2, LayoutDashboard, Package, Sparkles, ChefHat, ScanLine, Upload, Loader2, Check, X, BookOpen, AlertCircle, ShieldAlert, ShieldCheck, Settings, ArrowRight, Copy, RefreshCw, LogOut, Printer, BarChart3, Bell, BellOff, Calendar as CalendarIcon, Sun, Moon, Monitor, Thermometer, Droplets, Truck, ClipboardCheck, FileText, Globe } from 'lucide-react'
import { apiFetch, signOutAll, getChefToken } from '@/lib/apiClient'
import InstallAppPrompt from '@/components/InstallAppPrompt'
import LanguageSwitcher from '@/components/LanguageSwitcher'
import { useT } from '@/lib/i18n'
import { STATUS_META, EMPTY_FORM, ALLERGENS, CURRENCY_SYMBOL, guessShelfLifeDays, dateInDays, suggestExpiryDate, escapeText } from '@/components/shelfwise/shared'

// `fetch` inside this file transparently uses `apiFetch` (auth token attached).
const fetch = apiFetch

export function RecipeResult({ result, setResult, onBack, onClose, goToInventory, onSave, saving }) {
  const [genLoading, setGenLoading] = useState(false)
  const [newAllergen, setNewAllergen] = useState('')
  const [addingAllergen, setAddingAllergen] = useState(false)

  const addAllergen = () => {
    const v = newAllergen.trim().toLowerCase()
    if (!v) return
    const existing = (result.allergens || []).map(a => a.toLowerCase())
    if (existing.includes(v)) {
      toast.info('Already in the list')
      return
    }
    setResult({ ...result, allergens: [...(result.allergens || []), v] })
    setNewAllergen('')
    setAddingAllergen(false)
    toast.success(`Added "${v}" to allergens`)
  }

  const removeAllergen = (a) => {
    setResult({ ...result, allergens: (result.allergens || []).filter(x => x !== a) })
  }

  const generateInstructions = async () => {
    setGenLoading(true)
    try {
      const res = await fetch('/api/recipe-instructions', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          title: result.title || '',
          ingredients: (result.ingredients || result.matched || []).map(i => i.name || i),
          servings: result.servings || ''
        }),
      })
      const data = await res.json()
      if (!res.ok) throw new Error(data.error || 'Failed')
      setResult({ ...result, instructions: data.instructions || [], source: data.source || 'AI Generated' })
      toast.success('Cooking method generated by AI ✨')
    } catch (e) {
      toast.error(e.message || 'Could not generate cooking method')
    } finally {
      setGenLoading(false)
    }
  }
  const [scale, setScale] = useState(1)
  const scaleQty = (q) => {
    const n = Number(q) || 0
    const scaled = n * scale
    // pretty-format: integer if whole, else 2 decimals (trimmed)
    return Number.isInteger(scaled) ? scaled : Math.round(scaled * 100) / 100
  }
  return (
    <div className="space-y-5 py-2">
      {/* BIG allergen warning banner at the TOP — now editable */}
      <div className={`rounded-xl border-2 p-4 ${result.allergens?.length ? 'border-amber-300 bg-gradient-to-r from-amber-50 to-orange-50' : 'border-slate-200 bg-slate-50/40'}`}>
        <div className="flex items-start gap-3">
          <div className={`h-10 w-10 rounded-full flex items-center justify-center shrink-0 ${result.allergens?.length ? 'bg-amber-200' : 'bg-slate-200'}`}>
            <ShieldAlert className={`h-6 w-6 ${result.allergens?.length ? 'text-amber-700' : 'text-slate-500'}`} />
          </div>
          <div className="flex-1 min-w-0">
            <div className="flex items-center justify-between gap-2 flex-wrap">
              <p className={`text-sm font-bold uppercase tracking-wider ${result.allergens?.length ? 'text-amber-900' : 'text-slate-700'}`}>
                {result.allergens?.length ? '⚠️ Contains Allergens' : 'No allergens detected'}
              </p>
              {!addingAllergen && (
                <Button size="sm" variant="outline" onClick={() => setAddingAllergen(true)} className="h-7 px-2.5 text-xs border-amber-400 text-amber-800 hover:bg-amber-100">
                  <Plus className="h-3.5 w-3.5 mr-1" /> Add allergen
                </Button>
              )}
            </div>
            <p className={`text-xs mt-0.5 ${result.allergens?.length ? 'text-amber-800' : 'text-slate-600'}`}>
              {result.allergens?.length ? 'Review carefully before serving. Tap × to remove a wrong tag, or + to add a missing one.' : 'AI did not flag any. Use + to add one if you know it contains one.'}
            </p>
            <div className="flex flex-wrap gap-2 mt-2.5">
              {(result.allergens || []).map(a => (
                <span key={a} className="px-3 py-1 rounded-full bg-amber-200 text-amber-900 text-sm font-semibold capitalize border border-amber-400 inline-flex items-center gap-1.5">
                  {a}
                  <button onClick={() => removeAllergen(a)} className="hover:bg-amber-300 rounded-full h-5 w-5 flex items-center justify-center -mr-1" aria-label={`Remove ${a}`}>
                    <X className="h-3 w-3" />
                  </button>
                </span>
              ))}
              {addingAllergen && (
                <div className="inline-flex items-center gap-1.5 bg-white rounded-full border-2 border-amber-400 pl-3 pr-1 py-0.5">
                  <input
                    autoFocus
                    value={newAllergen}
                    onChange={e => setNewAllergen(e.target.value)}
                    onKeyDown={e => {
                      if (e.key === 'Enter') addAllergen()
                      if (e.key === 'Escape') { setAddingAllergen(false); setNewAllergen('') }
                    }}
                    placeholder="e.g. sesame, mustard..."
                    className="text-sm border-0 outline-none bg-transparent w-36"
                    maxLength={30}
                  />
                  <button onClick={addAllergen} className="h-6 w-6 rounded-full bg-emerald-600 text-white hover:bg-emerald-700 flex items-center justify-center">
                    <Check className="h-3.5 w-3.5" />
                  </button>
                  <button onClick={() => { setAddingAllergen(false); setNewAllergen('') }} className="h-6 w-6 rounded-full hover:bg-slate-100 flex items-center justify-center">
                    <X className="h-3.5 w-3.5" />
                  </button>
                </div>
              )}
            </div>
          </div>
        </div>
      </div>

      <div>
        <h3 className="text-2xl font-bold">{result.title || 'Recipe Analysis'}</h3>
        {result.servings && <p className="text-sm text-muted-foreground">{result.servings}</p>}
      </div>

      {/* Scale selector */}
      <div className="flex items-center gap-2 flex-wrap">
        <span className="text-xs font-semibold text-muted-foreground uppercase tracking-wider">Scale recipe</span>
        {[1, 2, 3, 4, 5].map(n => (
          <button key={n} onClick={() => setScale(n)}
            className={`h-9 w-12 rounded-lg border-2 font-bold text-sm transition ${scale === n ? 'border-purple-500 bg-purple-600 text-white' : 'border-slate-200 hover:border-purple-300 bg-white text-slate-700'}`}>
            {n}×
          </button>
        ))}
        {scale > 1 && <span className="text-xs text-muted-foreground italic">Quantities multiplied by {scale}</span>}
      </div>

      <div>
        <p className="font-semibold mb-2 text-sm">Ingredients ({result.matched?.length || 0})</p>
        <div className="border rounded-lg divide-y overflow-hidden max-h-[360px] overflow-y-auto">
          {(result.matched || []).map((m, i) => (
            <div key={i} className="flex items-center justify-between gap-3 px-4 py-2.5 hover:bg-slate-50">
              <div className="flex-1 min-w-0">
                <p className="font-medium text-sm capitalize">{m.name}</p>
                <p className="text-xs text-muted-foreground">{scaleQty(m.quantity)} {m.unit}{m.notes ? ` · ${m.notes}` : ''}</p>
              </div>
            </div>
          ))}
        </div>
      </div>

      {result.steps?.length > 0 && (
        <details className="border rounded-lg p-3">
          <summary className="font-semibold text-sm cursor-pointer">Cooking Steps ({result.steps.length})</summary>
          <ol className="list-decimal list-inside mt-2 space-y-1 text-sm text-muted-foreground">
            {result.steps.map((s, i) => <li key={i}>{s}</li>)}
          </ol>
        </details>
      )}

      {/* AI-generated cooking method (shown when original recipe has no instructions) */}
      <div className="border-2 border-purple-200 bg-purple-50/40 rounded-xl p-4">
        <div className="flex items-start justify-between gap-2 mb-2">
          <div>
            <p className="font-semibold text-sm flex items-center gap-1.5">👨‍🍳 Cooking Method</p>
            <p className="text-xs text-muted-foreground">
              {Array.isArray(result.instructions) && result.instructions.length > 0
                ? `AI-generated method · ${result.source || 'based on best recipe sources'}`
                : 'No cooking instructions in this recipe — let AI write them based on the ingredients.'}
            </p>
          </div>
          <Button size="sm" onClick={generateInstructions} disabled={genLoading} className="bg-purple-600 hover:bg-purple-700 shrink-0">
            {genLoading ? <><Loader2 className="h-3.5 w-3.5 mr-1.5 animate-spin" /> Cooking...</> : <><Sparkles className="h-3.5 w-3.5 mr-1.5" /> {Array.isArray(result.instructions) && result.instructions.length > 0 ? 'Regenerate' : 'Generate with AI'}</>}
          </Button>
        </div>
        {Array.isArray(result.instructions) && result.instructions.length > 0 && (
          <ol className="list-decimal list-outside ml-5 space-y-2 text-sm text-slate-700 mt-3">
            {result.instructions.map((step, i) => (
              <li key={i} className="leading-relaxed">{step}</li>
            ))}
          </ol>
        )}
      </div>

      <div className="flex justify-between pt-2 border-t">
        <Button variant="ghost" onClick={onBack}><X className="h-4 w-4 mr-2" /> Scan another</Button>
        <div className="flex gap-2">
          <Button variant="outline" onClick={onSave} disabled={saving}>
            {saving ? <><Loader2 className="h-4 w-4 mr-2 animate-spin" /> Saving...</> : <><Check className="h-4 w-4 mr-2" /> Save Recipe</>}
          </Button>
          <Button onClick={onClose} className="bg-purple-600 hover:bg-purple-700">Done</Button>
        </div>
      </div>
    </div>
  )
}

export function RecipesView({ recipes, search, setSearch, openRecipe, onView, onDelete, openRecipeGen, openRecipeGenFromExpiring, onSaved }) {
  const [tab, setTab] = useState('saved') // 'saved' | 'scan' | 'websearch'
  // Web recipe search state
  const [webQuery, setWebQuery] = useState('')
  const [webServings, setWebServings] = useState(1)
  const [webLoading, setWebLoading] = useState(false)
  const [webResults, setWebResults] = useState([])
  const [webSearched, setWebSearched] = useState(false)

  const runWebSearch = async () => {
    const q = webQuery.trim()
    if (!q) { toast.error('Type a dish name first, e.g. "Chicken Tikka Masala"'); return }
    setWebLoading(true)
    setWebResults([])
    try {
      const res = await fetch('/api/recipe/web-search', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ query: q, servings: webServings })
      })
      const data = await res.json()
      if (!res.ok) throw new Error(data.error || 'Search failed — try again')
      const list = Array.isArray(data.recipes) ? data.recipes : []
      if (list.length === 0) throw new Error('No recipes found — try a different dish name')
      setWebResults(list)
      setWebSearched(true)
      toast.success(`Found ${list.length} top recipes for "${q}"`)
    } catch (e) {
      toast.error(e.message || 'Search failed')
    } finally { setWebLoading(false) }
  }

  return (
    <div className="space-y-6">
      <div>
        <h2 className="text-3xl font-bold tracking-tight">Recipes</h2>
        <p className="text-muted-foreground mt-1">Browse saved recipes, search the web's best recipes, scan an existing one, or generate from ingredients with AI</p>
      </div>

      {/* Four-tab toggle */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-3">
        <button onClick={() => setTab('saved')}
          className={`text-left rounded-xl border-2 p-5 transition ${tab === 'saved' ? 'border-purple-500 bg-purple-50' : 'border-slate-200 hover:border-purple-300 bg-white'}`}>
          <div className="flex items-center gap-3">
            <div className={`h-11 w-11 rounded-lg flex items-center justify-center ${tab === 'saved' ? 'bg-purple-600 text-white' : 'bg-purple-100 text-purple-600'}`}>
              <BookOpen className="h-5 w-5" />
            </div>
            <div>
              <p className="font-semibold">Saved Recipes</p>
              <p className="text-xs text-muted-foreground">{recipes.length} recipe{recipes.length !== 1 ? 's' : ''} in your collection</p>
            </div>
          </div>
        </button>
        <button onClick={() => setTab('websearch')}
          className={`text-left rounded-xl border-2 p-5 transition relative ${tab === 'websearch' ? 'border-sky-500 bg-sky-50' : 'border-sky-200 hover:border-sky-400 bg-sky-50/40'}`}>
          <span className="absolute top-2 right-2 text-[9px] font-bold bg-sky-600 text-white rounded px-1.5 py-0.5">NEW</span>
          <div className="flex items-center gap-3">
            <div className={`h-11 w-11 rounded-lg flex items-center justify-center ${tab === 'websearch' ? 'bg-sky-600 text-white' : 'bg-sky-100 text-sky-600'}`}>
              <Globe className="h-5 w-5" />
            </div>
            <div>
              <p className="font-semibold">Search Web Recipes</p>
              <p className="text-xs text-muted-foreground">Type a dish → get the 3 best recipes with allergens + scaling</p>
            </div>
          </div>
        </button>
        <button onClick={() => { setTab('scan'); openRecipe() }}
          className={`text-left rounded-xl border-2 p-5 transition ${tab === 'scan' ? 'border-purple-500 bg-purple-50' : 'border-slate-200 hover:border-purple-300 bg-white'}`}>
          <div className="flex items-center gap-3">
            <div className={`h-11 w-11 rounded-lg flex items-center justify-center ${tab === 'scan' ? 'bg-purple-600 text-white' : 'bg-purple-100 text-purple-600'}`}>
              <ScanLine className="h-5 w-5" />
            </div>
            <div>
              <p className="font-semibold">Scan or Upload Recipe</p>
              <p className="text-xs text-muted-foreground">Paste text or upload a recipe photo</p>
            </div>
          </div>
        </button>
        <button onClick={() => { (openRecipeGenFromExpiring || openRecipeGen)() }}
          className="text-left rounded-xl border-2 p-5 transition border-rose-200 hover:border-rose-400 bg-rose-50 relative">
          <span className="absolute top-2 right-2 text-[9px] font-bold bg-rose-600 text-white rounded px-1.5 py-0.5">AI</span>
          <div className="flex items-center gap-3">
            <div className="h-11 w-11 rounded-lg flex items-center justify-center bg-rose-600 text-white">
              <Sparkles className="h-5 w-5" />
            </div>
            <div>
              <p className="font-semibold">Cook What's Expiring</p>
              <p className="text-xs text-muted-foreground">Expiring stock is loaded automatically → AI creates 3 recipes with allergens + timing</p>
            </div>
          </div>
        </button>
      </div>

      {tab === 'websearch' && (
        <Card className="border-0 shadow-sm">
          <CardContent className="pt-6 space-y-5">
            {/* Search bar */}
            <div className="flex flex-col sm:flex-row gap-2">
              <div className="relative flex-1">
                <Globe className="h-4 w-4 absolute left-3 top-1/2 -translate-y-1/2 text-sky-500" />
                <Input
                  className="pl-9"
                  placeholder='Type any dish name... e.g. "Chicken Tikka Masala", "Carbonara", "Butter Chicken"'
                  value={webQuery}
                  onChange={e => setWebQuery(e.target.value)}
                  onKeyDown={e => { if (e.key === 'Enter' && !webLoading) runWebSearch() }}
                />
              </div>
              <div className="flex items-center gap-2">
                <div className="flex items-center gap-1.5 shrink-0">
                  <Label className="text-xs text-muted-foreground whitespace-nowrap">Serves</Label>
                  <Input type="number" min="1" max="20" className="w-16" value={webServings}
                    onChange={e => setWebServings(Math.max(1, Math.min(20, Number(e.target.value) || 1)))} />
                </div>
                <Button onClick={runWebSearch} disabled={webLoading} className="bg-sky-600 hover:bg-sky-700 text-white">
                  {webLoading ? <Loader2 className="h-4 w-4 mr-1.5 animate-spin" /> : <Search className="h-4 w-4 mr-1.5" />}
                  {webLoading ? 'Searching...' : 'Find Best Recipes'}
                </Button>
              </div>
            </div>

            {/* Loading state */}
            {webLoading && (
              <div className="text-center py-14">
                <Loader2 className="h-10 w-10 mx-auto mb-3 animate-spin text-sky-500" />
                <p className="font-medium">Searching the web's best recipe sites...</p>
                <p className="text-sm text-muted-foreground mt-1">Comparing versions from BBC Good Food, Serious Eats, AllRecipes & more</p>
              </div>
            )}

            {/* Empty / hint state */}
            {!webLoading && webResults.length === 0 && (
              <div className="text-center py-14 text-muted-foreground">
                <Globe className="h-12 w-12 mx-auto mb-3 opacity-30" />
                <p className="font-medium">{webSearched ? 'No results — try another dish name' : 'Search any dish'}</p>
                <p className="text-sm mt-1">We'll find the 3 best versions from trusted cooking sites — with allergen warnings and 1x-5x scaling.</p>
                <div className="flex flex-wrap justify-center gap-2 mt-4">
                  {['Chicken Tikka Masala', 'Spaghetti Carbonara', 'Beef Wellington', 'Pad Thai'].map(s => (
                    <button key={s} onClick={() => { setWebQuery(s) }} className="px-3 py-1.5 rounded-full border border-sky-200 bg-sky-50 text-sky-700 text-xs font-medium hover:bg-sky-100 transition">
                      {s}
                    </button>
                  ))}
                </div>
              </div>
            )}

            {/* Results */}
            {!webLoading && webResults.length > 0 && (
              <div className="space-y-4">
                {webResults.map((r, idx) => (
                  <WebRecipeCard key={idx} recipe={r} onSaved={onSaved} />
                ))}
              </div>
            )}
          </CardContent>
        </Card>
      )}

      {tab === 'saved' && (
        <Card className="border-0 shadow-sm">
          <CardContent className="pt-6">
            <div className="relative max-w-md mb-4">
              <Search className="h-4 w-4 absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground" />
              <Input className="pl-9" placeholder="Search saved recipes..." value={search} onChange={e => setSearch(e.target.value)} />
            </div>

            {recipes.length === 0 ? (
              <div className="text-center py-16 text-muted-foreground">
                <BookOpen className="h-12 w-12 mx-auto mb-3 opacity-30" />
                <p className="font-medium">No saved recipes yet</p>
                <p className="text-sm">Click "Scan or Upload Recipe" above to start your collection.</p>
              </div>
            ) : (
              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
                {recipes.map(r => (
                  <button key={r.id} onClick={() => onView(r)} className="text-left">
                    <Card className="hover:shadow-md hover:-translate-y-0.5 transition cursor-pointer h-full">
                      <CardHeader className="pb-3">
                        <CardTitle className="text-base line-clamp-2">{r.title || 'Untitled'}</CardTitle>
                        {r.servings && <CardDescription>{r.servings}</CardDescription>}
                      </CardHeader>
                      <CardContent className="space-y-3">
                        {Array.isArray(r.allergens) && r.allergens.length > 0 && (
                          <div className="flex flex-wrap gap-1">
                            {r.allergens.slice(0, 5).map(a => (
                              <Badge key={a} variant="outline" className="bg-amber-50 text-amber-800 border-amber-300 capitalize text-[10px]">{a}</Badge>
                            ))}
                            {r.allergens.length > 5 && <Badge variant="outline" className="text-[10px]">+{r.allergens.length - 5}</Badge>}
                          </div>
                        )}
                        <div className="flex items-center justify-between text-xs text-muted-foreground">
                          <span>{Array.isArray(r.ingredients) ? r.ingredients.length : 0} ingredients</span>
                          <span>{r.created_at ? new Date(r.created_at).toLocaleDateString() : ''}</span>
                        </div>
                      </CardContent>
                    </Card>
                  </button>
                ))}
              </div>
            )}
          </CardContent>
        </Card>
      )}
    </div>
  )
}

export function WebRecipeCard({ recipe: r, onSaved }) {
  const [scale, setScale] = useState(1)
  const [showSteps, setShowSteps] = useState(false)
  const [saving, setSaving] = useState(false)
  const [saved, setSaved] = useState(false)

  const scaleQty = (q) => {
    const n = Number(q) || 0
    const scaled = n * scale
    return Number.isInteger(scaled) ? scaled : Math.round(scaled * 100) / 100
  }

  const saveRecipe = async () => {
    setSaving(true)
    try {
      const res = await fetch('/api/recipes', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          title: r.title,
          servings: `Serves ${r.servings || 4}`,
          ingredients: (r.ingredients || []).map(i => ({ name: i.name, quantity: i.quantity, unit: i.unit })),
          allergens: r.allergens || [],
          steps: r.steps || [],
          summary: {
            source: r.source || '',
            style: r.style || '',
            description: r.description || '',
            prepMinutes: r.prepMinutes || 0,
            cookMinutes: r.cookMinutes || 0,
            cuisine: r.cuisine || '',
            difficulty: r.difficulty || '',
            notes: r.notes || '',
          }
        })
      })
      if (!res.ok) throw new Error('Save failed')
      setSaved(true)
      toast.success(`"${r.title}" saved to your collection`)
      onSaved && onSaved()
    } catch (e) {
      toast.error(e.message || 'Failed to save recipe')
    } finally { setSaving(false) }
  }

  return (
    <div className="rounded-xl border-2 border-sky-100 bg-white overflow-hidden">
      {/* Header */}
      <div className="p-4 sm:p-5 bg-gradient-to-r from-sky-50 to-white border-b border-sky-100">
        <div className="flex flex-wrap items-center gap-2 mb-1.5">
          {r.style && <Badge className="bg-sky-600 text-white hover:bg-sky-600 text-[10px]">{r.style}</Badge>}
          {r.source && (
            <Badge variant="outline" className="border-sky-300 text-sky-700 bg-sky-50 text-[10px]">
              <Globe className="h-3 w-3 mr-1" /> Inspired by {r.source}
            </Badge>
          )}
        </div>
        <h3 className="text-lg font-bold leading-tight">{r.title}</h3>
        {r.description && <p className="text-sm text-muted-foreground mt-0.5">{r.description}</p>}
        <div className="flex flex-wrap gap-x-4 gap-y-1 mt-2 text-xs text-muted-foreground">
          <span className="inline-flex items-center gap-1"><Clock className="h-3.5 w-3.5" /> Prep {r.prepMinutes || 0} min</span>
          <span className="inline-flex items-center gap-1"><ChefHat className="h-3.5 w-3.5" /> Cook {r.cookMinutes || 0} min</span>
          {r.difficulty && <span className="capitalize inline-flex items-center gap-1"><BarChart3 className="h-3.5 w-3.5" /> {r.difficulty}</span>}
          {r.cuisine && <span>{r.cuisine}</span>}
        </div>
      </div>

      <div className="p-4 sm:p-5 space-y-4">
        {/* Allergens */}
        {Array.isArray(r.allergens) && r.allergens.length > 0 ? (
          <div className="rounded-lg border-2 border-amber-300 bg-amber-50 p-3">
            <div className="flex items-center gap-2">
              <ShieldAlert className="h-5 w-5 text-amber-700 shrink-0" />
              <p className="text-xs font-bold text-amber-900 uppercase tracking-wider">Contains Allergens</p>
            </div>
            <div className="flex flex-wrap gap-1.5 mt-2">
              {r.allergens.map(a => (
                <span key={a} className="px-2.5 py-0.5 rounded-full bg-amber-200 text-amber-900 text-xs font-semibold capitalize border border-amber-400">{a}</span>
              ))}
            </div>
          </div>
        ) : (
          <div className="rounded-lg border border-emerald-200 bg-emerald-50 p-3 flex items-center gap-2">
            <ShieldCheck className="h-5 w-5 text-emerald-600 shrink-0" />
            <p className="text-xs font-semibold text-emerald-800">No major allergens detected (always double-check labels)</p>
          </div>
        )}

        {/* Scale toggle */}
        <div className="flex items-center gap-2 flex-wrap">
          <span className="text-xs font-semibold text-muted-foreground uppercase tracking-wider">Scale recipe</span>
          {[1, 2, 3, 4, 5].map(n => (
            <button key={n} onClick={() => setScale(n)}
              className={`px-3 py-1 rounded-full text-sm font-bold transition border-2 ${scale === n ? 'bg-sky-600 text-white border-sky-600' : 'bg-white text-slate-600 border-slate-200 hover:border-sky-400'}`}>
              {n}x
            </button>
          ))}
          <span className="text-xs text-muted-foreground ml-1">= serves {(Number(r.servings) || 1) * scale}</span>
        </div>

        {/* Ingredients */}
        <div>
          <p className="text-sm font-bold mb-2">Ingredients {scale > 1 && <span className="text-sky-600">(scaled {scale}x)</span>}</p>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-x-4 gap-y-1.5">
            {(r.ingredients || []).map((i, idx) => (
              <div key={idx} className="flex items-baseline gap-2 text-sm">
                <span className="font-semibold text-sky-700 whitespace-nowrap">{scaleQty(i.quantity) || ''} {i.unit || ''}</span>
                <span className="text-slate-700">{i.name}</span>
              </div>
            ))}
          </div>
        </div>

        {/* Steps (collapsible) */}
        <div>
          <button onClick={() => setShowSteps(s => !s)} className="text-sm font-bold text-sky-700 hover:text-sky-900 inline-flex items-center gap-1">
            {showSteps ? 'Hide method' : `Show method (${(r.steps || []).length} steps)`}
            <ArrowRight className={`h-3.5 w-3.5 transition-transform ${showSteps ? 'rotate-90' : ''}`} />
          </button>
          {showSteps && (
            <ol className="mt-2 space-y-2">
              {(r.steps || []).map((s, idx) => (
                <li key={idx} className="flex gap-2.5 text-sm">
                  <span className="h-5 w-5 rounded-full bg-sky-100 text-sky-700 text-xs font-bold flex items-center justify-center shrink-0 mt-0.5">{idx + 1}</span>
                  <span className="text-slate-700">{String(s).replace(/^\d+\.\s*/, '')}</span>
                </li>
              ))}
            </ol>
          )}
          {showSteps && r.notes && (
            <p className="mt-3 text-xs text-muted-foreground italic border-l-2 border-sky-200 pl-3">💡 {r.notes}</p>
          )}
        </div>

        {/* Actions */}
        <div className="flex justify-end pt-1">
          <Button onClick={saveRecipe} disabled={saving || saved}
            className={saved ? 'bg-emerald-600 hover:bg-emerald-600 text-white' : 'bg-sky-600 hover:bg-sky-700 text-white'}>
            {saving ? <Loader2 className="h-4 w-4 mr-1.5 animate-spin" /> : saved ? <Check className="h-4 w-4 mr-1.5" /> : <BookOpen className="h-4 w-4 mr-1.5" />}
            {saved ? 'Saved to Collection' : 'Save Recipe'}
          </Button>
        </div>
      </div>
    </div>
  )
}

export function ViewRecipeDialog({ recipe, onClose, onDelete }) {
  const [scale, setScale] = useState(1)
  useEffect(() => { setScale(1) }, [recipe?.id])
  const scaleQty = (q) => {
    const n = Number(q) || 0
    const scaled = n * scale
    return Number.isInteger(scaled) ? scaled : Math.round(scaled * 100) / 100
  }
  if (!recipe) return null
  return (
    <Dialog open={!!recipe} onOpenChange={(v) => { if (!v) onClose() }}>
      <DialogContent className="sm:max-w-[760px] max-h-[92vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2"><BookOpen className="h-5 w-5 text-purple-600" /> {recipe.title || 'Untitled recipe'}</DialogTitle>
          {recipe.servings && <p className="text-sm text-muted-foreground">{recipe.servings}</p>}
        </DialogHeader>

        {Array.isArray(recipe.allergens) && recipe.allergens.length > 0 && (
          <div className="rounded-xl border-2 border-amber-300 bg-gradient-to-r from-amber-50 to-orange-50 p-4">
            <div className="flex items-start gap-3">
              <div className="h-10 w-10 rounded-full bg-amber-200 flex items-center justify-center shrink-0">
                <ShieldAlert className="h-6 w-6 text-amber-700" />
              </div>
              <div className="flex-1">
                <p className="text-sm font-bold text-amber-900 uppercase tracking-wider">⚠️ Contains Allergens</p>
                <div className="flex flex-wrap gap-2 mt-2">
                  {recipe.allergens.map(a => (
                    <span key={a} className="px-3 py-1 rounded-full bg-amber-200 text-amber-900 text-sm font-semibold capitalize border border-amber-400">{a}</span>
                  ))}
                </div>
              </div>
            </div>
          </div>
        )}

        <div className="flex items-center gap-2 flex-wrap">
          <span className="text-xs font-semibold text-muted-foreground uppercase tracking-wider">Scale recipe</span>
          {[1, 2, 3, 4, 5].map(n => (
            <button key={n} onClick={() => setScale(n)}
              className={`h-9 w-12 rounded-lg border-2 font-bold text-sm transition ${scale === n ? 'border-purple-500 bg-purple-600 text-white' : 'border-slate-200 hover:border-purple-300 bg-white text-slate-700'}`}>
              {n}×
            </button>
          ))}
          {scale > 1 && <span className="text-xs text-muted-foreground italic">Quantities multiplied by {scale}</span>}
        </div>

        <div>
          <p className="font-semibold text-sm mb-2">Ingredients</p>
          <ul className="space-y-1 text-sm border rounded-lg divide-y">
            {(recipe.ingredients || []).map((ing, i) => (
              <li key={i} className="px-3 py-2 flex justify-between">
                <span className="capitalize">{ing.name}</span>
                <span className="text-muted-foreground">{scaleQty(ing.quantity)} {ing.unit}{ing.notes ? ` · ${ing.notes}` : ''}</span>
              </li>
            ))}
          </ul>
        </div>

        {recipe.steps?.length > 0 && (
          <div>
            <p className="font-semibold text-sm mb-2">Cooking Steps</p>
            <ol className="list-decimal list-inside space-y-1 text-sm text-muted-foreground">
              {recipe.steps.map((s, i) => <li key={i}>{s}</li>)}
            </ol>
          </div>
        )}

        {Array.isArray(recipe.instructions) && recipe.instructions.length > 0 && (
          <div className="border-2 border-purple-200 bg-purple-50/40 rounded-xl p-4">
            <p className="font-semibold text-sm mb-1 flex items-center gap-1.5">👨‍🍳 Cooking Method <span className="text-[10px] font-normal text-muted-foreground">{recipe.source || '· AI-generated'}</span></p>
            <ol className="list-decimal list-outside ml-5 space-y-2 text-sm text-slate-700 mt-2">
              {recipe.instructions.map((s, i) => <li key={i} className="leading-relaxed">{s}</li>)}
            </ol>
          </div>
        )}

        <DialogFooter>
          <Button variant="ghost" className="text-red-600 hover:bg-red-50" onClick={() => { onDelete(recipe.id); onClose() }}>
            <Trash2 className="h-4 w-4 mr-2" /> Delete
          </Button>
          <Button onClick={onClose} className="bg-purple-600 hover:bg-purple-700">Close</Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  )
}

export function RecipeGenDialog({ open, onClose, seed = [], inventoryNames = [] }) {
  const [ingredients, setIngredients] = useState([])
  const [current, setCurrent] = useState('')
  const [servings, setServings] = useState(1)  // flexible default — start at 1 so single-portion meals work
  const [cuisine, setCuisine] = useState('Any')
  const [dietary, setDietary] = useState([])
  const [skillLevel, setSkillLevel] = useState('easy')
  const [loading, setLoading] = useState(false)
  const [recipes, setRecipes] = useState([])
  const [expandedIdx, setExpandedIdx] = useState(0)

  // Reset every time the dialog opens; seed with expiring items if provided.
  useEffect(() => {
    if (open) {
      setIngredients(Array.isArray(seed) ? [...new Set(seed)] : [])
      setCurrent('')
      setServings(1)
      setCuisine('Any')
      setDietary([])
      setSkillLevel('easy')
      setRecipes([])
      setExpandedIdx(0)
    }
  }, [open, seed])

  const addFromInput = () => {
    const val = current.trim()
    if (!val) return
    // Support comma-separated bulk paste
    const parts = val.split(',').map(s => s.trim()).filter(Boolean)
    setIngredients(list => [...new Set([...list, ...parts])])
    setCurrent('')
  }

  const removeIngredient = (name) => setIngredients(list => list.filter(x => x !== name))

  const toggleDietary = (d) => setDietary(list => list.includes(d) ? list.filter(x => x !== d) : [...list, d])

  const generate = async () => {
    if (ingredients.length === 0) { toast.error('Add at least one ingredient'); return }
    setLoading(true)
    setRecipes([])
    try {
      const res = await fetch('/api/recipe/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          ingredients,
          servings,
          cuisine: cuisine === 'Any' ? '' : cuisine,
          dietary,
          skillLevel,
        }),
      })
      if (!res.ok) throw new Error('AI failed — try again')
      const data = await res.json()
      const list = Array.isArray(data.recipes) ? data.recipes : []
      if (list.length === 0) throw new Error('AI returned no recipes')
      setRecipes(list)
      setExpandedIdx(0)
      toast.success(`✨ ${list.length} recipe${list.length !== 1 ? 's' : ''} generated`)
    } catch (e) {
      toast.error(e.message || 'Could not generate')
    } finally { setLoading(false) }
  }

  const printRecipe = (r) => {
    const w = window.open('', '_blank', 'width=700,height=800')
    if (!w) return toast.error('Popup blocked')
    const html = `<!doctype html><html><head><title>${escapeText(r.title)}</title>
<style>
  body { font-family: -apple-system,BlinkMacSystemFont,Segoe UI,sans-serif; padding: 24px; color: #111; max-width: 720px; margin: 0 auto; }
  h1 { border-bottom: 3px solid #059669; padding-bottom: 8px; margin: 0 0 8px; }
  .meta { color: #64748b; font-size: 13px; margin-bottom: 6px; }
  .badges { margin: 8px 0 16px; }
  .badge { display:inline-block; padding: 3px 8px; border-radius: 4px; font-size: 11px; font-weight: 600; margin-right: 4px; }
  .b-allergen { background: #fef3c7; color: #92400e; }
  .b-time { background: #dcfce7; color: #166534; }
  h2 { color: #059669; margin-top: 20px; border-bottom: 1px solid #ddd; padding-bottom: 3px; }
  ul, ol { padding-left: 20px; }
  li { margin: 4px 0; }
  @media print { body { padding: 12px; } }
</style></head><body>
<h1>${escapeText(r.title)}</h1>
<div class="meta">${escapeText(r.description || '')}</div>
<div class="badges">
  <span class="badge b-time">⏱ Prep ${r.prepMinutes || 0} min</span>
  <span class="badge b-time">🔥 Cook ${r.cookMinutes || 0} min</span>
  <span class="badge b-time">🍽 Serves ${r.servings || servings}</span>
  <span class="badge b-time">📋 ${r.difficulty || 'easy'}</span>
  ${(r.allergens || []).map(a => `<span class="badge b-allergen">⚠ ${escapeText(a)}</span>`).join('')}
</div>
<h2>Ingredients</h2>
<ul>${(r.ingredients || []).map(i => `<li>${i.quantity || ''} ${escapeText(i.unit || '')} — <b>${escapeText(i.name || '')}</b>${i.pantry ? ' <em>(pantry)</em>' : ''}</li>`).join('')}</ul>
<h2>Method</h2>
<ol>${(r.steps || []).map(s => `<li>${escapeText(String(s).replace(/^\d+\.\s*/, ''))}</li>`).join('')}</ol>
${r.notes ? `<h2>Chef's Note</h2><p>${escapeText(r.notes)}</p>` : ''}
<div style="margin-top: 32px; font-size: 11px; color: #94a3b8; border-top: 1px solid #eee; padding-top: 8px">Generated by ShelfWise · shelfwise.co.in</div>
<script>window.onload=()=>setTimeout(()=>window.print(),400)</script>
</body></html>`
    w.document.write(html); w.document.close()
  }

  return (
    <Dialog open={open} onOpenChange={(v) => { if (!v) onClose() }}>
      <DialogContent className="sm:max-w-2xl max-h-[92vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">✨ AI Recipe Generator</DialogTitle>
          <p className="text-sm text-muted-foreground">
            Pick ingredients → we suggest 3 recipes. Prioritises using what's expiring first.
          </p>
        </DialogHeader>

        <div className="space-y-4 py-2">
          {/* Ingredients input */}
          <div>
            <Label className="text-sm font-semibold">🥕 Ingredients ({ingredients.length})</Label>
            <div className="flex gap-2 mt-1">
              <Input
                value={current}
                placeholder="Type an ingredient (or paste multiple, comma-separated)"
                onChange={e => setCurrent(e.target.value)}
                onKeyDown={e => { if (e.key === 'Enter') { e.preventDefault(); addFromInput() } }}
                list="rg-inv-suggest"
              />
              <datalist id="rg-inv-suggest">
                {inventoryNames.slice(0, 200).map(n => <option key={n} value={n} />)}
              </datalist>
              <Button type="button" onClick={addFromInput} disabled={!current.trim()}><Plus className="h-4 w-4" /></Button>
            </div>
            {ingredients.length === 0 && (
              <p className="text-xs text-slate-500 mt-2">💡 Tap into the box to see suggestions from your inventory. Or use the "Cook Expiring" button on the Dashboard to auto-fill.</p>
            )}
            {ingredients.length > 0 && (
              <div className="flex flex-wrap gap-1.5 mt-2">
                {ingredients.map(ing => (
                  <span key={ing} className="inline-flex items-center gap-1 rounded-full bg-emerald-100 text-emerald-900 px-2.5 py-1 text-xs font-medium">
                    {ing}
                    <button type="button" onClick={() => removeIngredient(ing)} className="hover:text-red-700"><X className="h-3 w-3" /></button>
                  </span>
                ))}
              </div>
            )}
          </div>

          {/* Options row */}
          <div className="grid grid-cols-2 md:grid-cols-4 gap-2">
            <div>
              <Label className="text-xs">Servings</Label>
              <Input type="number" min="1" max="20" value={servings} onChange={e => setServings(Math.max(1, Math.min(20, Number(e.target.value) || 1)))} />
            </div>
            <div>
              <Label className="text-xs">Cuisine</Label>
              <Select value={cuisine} onValueChange={setCuisine}>
                <SelectTrigger><SelectValue /></SelectTrigger>
                <SelectContent>
                  {['Any','Indian','Italian','Chinese','Mexican','British','French','Thai','Japanese','Mediterranean','Middle Eastern','American','Vegetarian','Bakery'].map(c => (
                    <SelectItem key={c} value={c}>{c}</SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            <div>
              <Label className="text-xs">Difficulty</Label>
              <Select value={skillLevel} onValueChange={setSkillLevel}>
                <SelectTrigger><SelectValue /></SelectTrigger>
                <SelectContent>
                  <SelectItem value="easy">Easy (≤ 30 min)</SelectItem>
                  <SelectItem value="medium">Medium (30-60 min)</SelectItem>
                  <SelectItem value="hard">Hard (60+ min)</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div>
              <Label className="text-xs">Dietary</Label>
              <div className="flex flex-wrap gap-1 mt-1">
                {['Vegetarian','Vegan','Gluten-free','Halal','Dairy-free'].map(d => (
                  <button
                    key={d}
                    type="button"
                    onClick={() => toggleDietary(d)}
                    className={`text-[11px] px-2 py-0.5 rounded-full border ${dietary.includes(d) ? 'bg-emerald-600 text-white border-emerald-600' : 'bg-white text-slate-600 border-slate-300'}`}
                  >{d}</button>
                ))}
              </div>
            </div>
          </div>

          <Button onClick={generate} disabled={loading || ingredients.length === 0} className="w-full bg-emerald-600 hover:bg-emerald-700 py-6 text-base">
            {loading ? <><Loader2 className="h-5 w-5 animate-spin mr-2" /> Generating (15-30 sec)…</> : <>✨ Generate {ingredients.length > 0 ? `${Math.min(3, 5)} recipes` : 'recipes'}</>}
          </Button>

          {/* Results */}
          {recipes.length > 0 && (
            <div className="space-y-3 pt-2">
              <p className="text-sm font-semibold text-emerald-700">🍳 {recipes.length} recipe{recipes.length !== 1 ? 's' : ''} generated — tap any to see full details</p>
              {recipes.map((r, i) => {
                const expanded = expandedIdx === i
                return (
                  <div key={i} className={`rounded-xl border-2 transition ${expanded ? 'border-emerald-400 bg-emerald-50/30' : 'border-slate-200 bg-white'}`}>
                    <button type="button" onClick={() => setExpandedIdx(expanded ? -1 : i)} className="w-full text-left p-3">
                      <div className="flex items-start justify-between gap-2">
                        <div className="min-w-0 flex-1">
                          <p className="font-bold text-slate-900">{r.title}</p>
                          {r.description && <p className="text-xs text-slate-600 mt-0.5">{r.description}</p>}
                          <div className="flex flex-wrap gap-1 mt-2">
                            <Badge variant="outline" className="bg-emerald-50 text-emerald-800 border-emerald-200 text-[10px]">⏱ {r.prepMinutes || 0}+{r.cookMinutes || 0} min</Badge>
                            <Badge variant="outline" className="bg-blue-50 text-blue-800 border-blue-200 text-[10px]">🍽 {r.servings || servings}</Badge>
                            <Badge variant="outline" className="bg-slate-50 text-slate-700 border-slate-200 text-[10px] capitalize">{r.difficulty || 'easy'}</Badge>
                            {r.cuisine && <Badge variant="outline" className="bg-purple-50 text-purple-800 border-purple-200 text-[10px]">{r.cuisine}</Badge>}
                            {(r.allergens || []).slice(0, 4).map(a => (
                              <Badge key={a} variant="outline" className="bg-amber-50 text-amber-800 border-amber-200 text-[10px]">⚠ {a}</Badge>
                            ))}
                          </div>
                        </div>
                        <ArrowRight className={`h-4 w-4 shrink-0 mt-1 transition-transform ${expanded ? 'rotate-90 text-emerald-600' : 'text-slate-400'}`} />
                      </div>
                    </button>

                    {expanded && (
                      <div className="border-t px-3 py-3 space-y-3">
                        <div>
                          <p className="text-xs font-bold uppercase text-slate-500 mb-1">Ingredients</p>
                          <ul className="text-sm space-y-1">
                            {(r.ingredients || []).map((ing, j) => (
                              <li key={j} className="flex items-baseline gap-2">
                                <span className="text-slate-400 shrink-0 w-16">{ing.quantity || ''} {ing.unit || ''}</span>
                                <span className={ing.pantry ? 'text-slate-500 italic' : 'text-slate-900 font-medium'}>{ing.name}{ing.pantry ? ' (pantry)' : ''}</span>
                              </li>
                            ))}
                          </ul>
                        </div>
                        <div>
                          <p className="text-xs font-bold uppercase text-slate-500 mb-1">Method</p>
                          <ol className="text-sm space-y-1.5 list-decimal pl-5">
                            {(r.steps || []).map((s, j) => (
                              <li key={j}>{String(s).replace(/^\d+\.\s*/, '')}</li>
                            ))}
                          </ol>
                        </div>
                        {r.notes && (
                          <div className="bg-emerald-50 border border-emerald-200 rounded-lg p-2 text-xs text-emerald-900">
                            💡 <b>Chef's note:</b> {r.notes}
                          </div>
                        )}
                        <div className="flex gap-2 pt-2">
                          <Button size="sm" variant="outline" onClick={() => printRecipe(r)} className="flex-1">
                            <Printer className="h-4 w-4 mr-1" /> Print
                          </Button>
                        </div>
                      </div>
                    )}
                  </div>
                )
              })}
            </div>
          )}
        </div>

        <DialogFooter>
          <Button variant="outline" onClick={onClose}>Close</Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  )
}

